spring.application.name=SpringBoot-BankManagementApplication

server.port=8080

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_management
spring.datasource.username=postgres
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect